# Generated by Django 5.1.15 on 2026-08-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField()),
                ('chat_username', models.CharField(blank=True, max_length=64)),
                ('query_text', models.CharField(max_length=255)),
                ('place_label', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('probe_ever_found', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['chat_id'], name='subscriptio_chat_id_9538d9_idx')],
            },
        ),
    ]
